# Generated by Django 3.0.1 on 2019-12-29 10:40

import Aydat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aydat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanim',
            name='kurum_yonetici',
            field=models.ForeignKey(on_delete=models.SET(Aydat.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='uye',
            name='kurum',
        ),
        migrations.AddField(
            model_name='uye',
            name='kurum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aydat.Tanim'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alinan', models.CharField(max_length=10, verbose_name='Ödenen')),
                ('Tarih_odeme', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aydat.Uye')),
            ],
        ),
    ]
