# Generated by Django 3.0.1 on 2019-12-29 10:48

import Aydat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aydat', '0002_auto_20191229_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanim',
            name='kurum_yonetici',
            field=models.ForeignKey(auto_created=True, on_delete=models.SET(Aydat.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
