# Generated by Django 3.0.1 on 2019-12-29 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aydat', '0006_auto_20191229_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uye',
            name='kurum',
        ),
        migrations.AddField(
            model_name='uye',
            name='Uye_kurum',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kurum', to='Aydat.Tanim'),
        ),
    ]
