# Generated by Django 3.0.1 on 2019-12-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aydat', '0007_auto_20191229_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uye',
            old_name='Uye_kurum',
            new_name='kurum',
        ),
    ]
