# Generated by Django 3.0.1 on 2019-12-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aydat', '0008_auto_20191229_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='kurum',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kurum', to='Aydat.Tanim'),
        ),
    ]
