# Generated by Django 3.0.1 on 2019-12-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aydat', '0009_auto_20191229_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='kurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aydat.Tanim'),
        ),
    ]
