# Generated by Django 3.0.1 on 2019-12-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurum',
            options={'verbose_name': 'Sorumlu kişi'},
        ),
        migrations.AddField(
            model_name='kurum',
            name='idare',
            field=models.CharField(default='', max_length=50, verbose_name='Sorumlu Kişi'),
        ),
    ]
